### ISSUE TITLE
FAWE max-changes not being enforced correctly

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1062]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I want to set the maximum block changes limit to 500,000 blocks but for some reason the server uses a much lower limit?
Here's what I have in the config:

```
limits:
  default:
    # Max actions that can be run concurrently (i.e. commands)
    max-actions: 1
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 500000
    # Max number of blocks checked (e.g. `//count stone` which doesn't change blocks)
    max-checks: 500000
    # Number of times a change can fail (e.g. if the player can't access that region)
    max-fails: 0
```

When doing a large flat edit on the ground of a plot and having only 255,025 blocks selected the plugin doesn't allow the edit go through because it thinks too many blocks are being changed:
![2021-05-09_14 15 27](https://user-images.githubusercontent.com/10485646/117573654-13b1b980-b0d1-11eb-9402-95ebe6915e01.png)

When lowering my selection to just 181,900 blocks it still thinks I'm trying to change too many blocks but sets blocks partially:
![image](https://user-images.githubusercontent.com/10485646/117573717-7014d900-b0d1-11eb-8118-b808750f5a2b.png)

You can see here where it randomly cuts off:
![2021-05-09_14 21 06](https://user-images.githubusercontent.com/10485646/117573798-ce41bc00-b0d1-11eb-95b2-b1edecb6cb7d.png)

I'm only changing around 250k blocks with a max changes limit of 500k so it should let the edit go through but I have no idea what it is doing to determine that the change is too big. This can also cause strange issues where you do an edit and the server thinks you've hit the block limit but it will still place some of the blocks and you will not be able to undo the edit.

### To Reproduce

1. Change the max-changes limit in the config to 500,000
2. Select the corner ground block of a large plot
2. Select the opposite corner ground block of a large plot
3. Do a //set operation where 250k blocks change

### Expected behaviour

The max-changes limit should be enforced using the correct limit specified.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/92f7ead07a564edd96f3087131d82683

### Fawe Version

FastAsyncWorldEdit version 1.16-673;00d689a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.
