### ISSUE TITLE
WorldEdit logging file does not get created / logged to.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#1622]
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

The vanilla worldedit.log file does not seem to get created and logged to. This use to function in FAWE but broke some months ago.

### To Reproduce

worldedit-config.yml
```
logging:
    log-commands: true
    file: worldedit.log
    # The format of custom log message. This is java general format string (java.util.Formatter). Arguments are:
    #   1$ : date - a Date object representing event time of the log record.
    #   2$ : source - a string representing the caller, if available; otherwise, the logger's name.
    #   3$ : logger - the logger's name.
    #   4$ : level - the log level.
    #   5$ : message - the formatted log message returned from the Formatter.formatMessage(LogRecord) method. It uses java.text formatting and does not use the java.util.Formatter format argument.
    #   6$ : thrown - a string representing the throwable associated with the log record and its backtrace beginning with a newline character, if any; otherwise, an empty string.
    # For details see:
    #   https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
    #   https://docs.oracle.com/javase/8/docs/api/java/util/logging/SimpleFormatter.html#format-java.util.logging.LogRecord-
    format: "[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s]: %5$s%6$s%n"
```

### Expected behaviour

WorldEdit actions to be logged in a worldedit.log file.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8d5bb060b4f8452eb3f4bf7c5591b328

### Fawe Version

FastAsyncWorldEdit version 2.0.2-SNAPSHOT-100;39081e6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.
