### ISSUE TITLE
Bad calculation of the number of blocks changed?

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit#1874]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I have currently some problems with max-changed limitation.

I have a rank named 'builder-plus' with 8 millions max-change

```yaml
limits:
[some-line]
  builder-plus:
    # Max actions that can be run concurrently (i.e. commands)
    max-actions: 2
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 8000000
    # Max number of blocks checked (e.g. `//count stone` which doesn't change blocks)
    max-checks: 80000000
    # Number of times a change can fail (e.g. if the player can't access that region)
    max-fails: 4000000
    # Allowed brush iterations (e.g. `//brush smooth`)
    max-iterations: 500
[some-line]
```

But with `//pos1` `//pos2` and `//set stone` they are limited to 2.5 millions blocks.

I have checked, the permission is well configured, here exemple of luck perms record:
![image](https://user-images.githubusercontent.com/472429/178974058-b6e61d27-8f34-4638-85d6-aa97a444944b.png)

### To Reproduce

1. Define limitation
2. Check permission to be limited
3. Try the limitation with simple `//set stone`

### Expected behaviour

I suppose there are complicated to fix this kind of bug.

Many add some step into resolution of this bug : 
As add log or complete the error message with value compared (current max-changed of player and current selection count) ?

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/472429/178973090-95527097-c1a4-48f1-8ebf-40d49e00ab92.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6e996039991c46ef9176dc2941395c5c

### Fawe Version

FastAsyncWorldEdit-2.4.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.
