### ISSUE TITLE
Broken lighting when using WorldEdit operations.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#459]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config: https://paste.ubuntu.com/p/9hDB8hdgSM/
config-legacy: https://paste.ubuntu.com/p/MkQDTRFwNw/

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit dev 217

**[REQUIRED] Spigot/Paper Version Number:** 
Paper dev 273 (Spigot 1.15.2)

**[REQUIRED] Description of the problem:**
Chunk relighting is broken when doing worldedit operations.

**How to replicate**:
* Make a 2 point selection.
* //replace air

![link](https://i.imgur.com/GCGAHyy.png)
![link](https://i.imgur.com/xacygYZ.png)

Also tested with these changes.

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
  # If existing lighting should be removed before relighting
  remove-first: false
```
```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  # If existing lighting should be removed before relighting
  remove-first: true
```
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin
