### ISSUE TITLE
PlotSquared reset issue on augmented terrain

### ISSUE THREAD

**Issue by MOHMOBILE** [IntellectualSites/FastAsyncWorldEdit#816]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/ff8947fd80ed4e8a8248beb1bdcc6f69

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  1.16-489;b60d9ef
- Spigot/Paper Version Number (`/version`): Paper 1.16 340
- Minecraft Version: [e.g. 1.16.4]: 1.16.4

**Describe the bug**
The bug is that if I try to use it with PlotSquared to reset a plot, the plot border gets resetted, but the plot itself won't.

**To Reproduce**
1. Install PlotSquared and FAWE
2. But a plot
3. Reset the plot

**Plugins being used on the server**
You can see them in the debug.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin*

* I already wrote the developers of PlotSquared, but they said I should try it here.

**Comment by flowl** [comment]
Having the same issue on a fresh setup (LuckPerms, everything set + /op) with versions:

FastAsyncWorldEdit 1.16-511;91de441
PlotSquared 5.13.10-Premium

Only borders and roads get reset but nothing inside the plot.

**Comment by flowl** [comment]
@dordsor21 can I provide anything for you to be able to replicate the issue?

Here is my P2 world config (generated from `/p setup`):

```
configuration_version: v5
worlds:
  g1:
    plot:
      height: 62
      size: 43
      filling: minecraft:dirt
      floor: minecraft:grass_block
      bedrock: true
      biome: minecraft:forest
      auto_merge: false
      create_signs: true
    wall:
      block: minecraft:stone_slab
      block_claimed: minecraft:quartz_slab
      place_top_block: true
      filling: minecraft:stone
      height: 62
    road:
      width: 7
      height: 62
      block: minecraft:stone
      flags: {}
    generator:
      type: AUGMENTED
      terrain: ROAD
      plugin: PlotSquared
    misc_spawn_unowned: false
    home:
      nonmembers: side
      default: side
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    chat:
      forced: false
      enabled: true
    economy:
      prices:
        merge: 100
        sell: 100
        claim: 100
      use: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
    event:
      spawn:
        egg: false
        breeding: false
        custom: true
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags: {}
```
