### ISSUE TITLE
Rain falls through blocks made with WorldEdit.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#891]
FAWE Config
https://paste.gg/p/anonymous/1a54d54862624933848f14253d261f4f/files/5c422213b9a6480fb12d9bcd8feca2dd/raw
Config-legacy
https://paste.gg/p/anonymous/f62c6d5d81c6470091b49a2c6c032e50/files/33519430bb7b4eb59255f91a38ec064e/raw

**Required Information**
- FastAsyncWorldEdit-1.16 dev 585
- Paper dev 457
- Minecraft 1.16.5

**Describe the bug**
Rain falls through all blocks created with WorldEdit.
https://imgur.com/a/S1bz5IC

**To Reproduce**
1. Do a WorldEdit operation (such as //hcyl)
2. Turn on rain.
3. See rain fall through blocks.

I am able to fix the issue by forcing ``//fixlighting`` over the broken blocks/chunks.

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
  # If existing lighting should be removed before relighting
  remove-first: true
  # Calculate and set heightmaps when relighting
  do-heightmaps: true
```

I assume this is caused by the relighting still being broken? Here's me doing a very simple //cut operation and lighting being broken.
https://imgur.com/a/Bxh37u2

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

Old issues resurfaced?
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/632
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/633
