### ISSUE TITLE
limits.strip-nbt not working

### ISSUE THREAD

**Issue by Over2Craft-mc** [IntellectualSites/FastAsyncWorldEdit#939]
**Describe the bug**

limits.strip-nbt is not working. When a player is affected by a limit which contains block to strip nbt from, nbt are not stripped. 

**To Reproduce**

1. Configure a limit for example 
```yml
limits:
  default:
    max-actions: 1
    max-changes: 5
    max-checks: 5
    max-fails: 5
    max-iterations: 1000
    max-entities: 1337
    max-blockstates: 0
    max-history-mb: -1
    max-expression-ms: 50
    speed-reduction: 0
    fast-placement: true
    inventory-mode: 0
    confirm-large: true
    # List of blocks to strip nbt from
    strip-nbt: 
    - "minecraft:chest"
    - "CHEST"
```

2. Place some item in a chest

3. Give default limit permissions 

4. Copy paste the chest

**Expected behaviour**

Content of the chest shouldn't be copied if it is listed in "strip-nbt".

**Screenshots / Videos**

_No response_

**Error log (if applicable)**

_No response_

**Fawe Debugpaste**

https://athion.net/ISPaster/paste/view/18e46f3a021a42d98ba66adb829f0de8

**Fawe Version**

Fastasyncworldedit Version: 1.16-612;1a3f479

**Additional Context**

_No response_
